// Where the props and items go in the maze generated by C. They are placed on
// open floor around the spawn: the map book right there, the chest close, the
// potions a bit further, and the sword as far as possible (a reward for
// exploring).
import { ITEMS, type ItemKind, POTION_IDS } from "./items";
import type { TileMap } from "./tile-map";

// A sprite placed in the world, with its feet (bottom center) at (x, y).
export interface Prop {
  sprite: string; // asset name in public/assets
  x: number;
  y: number;
  animation?: string; // animation tag to loop
  frame?: number; // fixed frame, for sheets used as a set of variants
  pickup?: ItemKind; // walking over it puts it in the inventory
}

// Every sprite the items can use, so they can be loaded up front.
export const ITEM_SPRITES = ["Cofre_comun", ...new Set(Object.values(ITEMS).map((i) => i.sprite))];

const BOOK_DISTANCE = 48;
const CHEST_MIN_DISTANCE = 64;
const POTION_MIN_DISTANCE = 96;
const POTION_SPACING = 48;

interface Spot {
  x: number;
  y: number;
  distance: number;
}

export function placeItems(map: TileMap, spawn: { x: number; y: number }): Prop[] {
  const spots = openSpots(map, spawn);
  const taken: Spot[] = [];
  const free = (s: Spot, spacing: number) =>
    taken.every((t) => Math.hypot(t.x - s.x, t.y - s.y) >= spacing);
  const take = (s: Spot | undefined) => {
    if (s) taken.push(s);
    return s;
  };

  const props: Prop[] = [];
  const book = take(spots.find((s) => s.distance >= BOOK_DISTANCE));
  if (book) props.push(item("map_book", book));

  const chest = take(spots.find((s) => s.distance >= CHEST_MIN_DISTANCE && free(s, POTION_SPACING)));
  if (chest) props.push({ sprite: "Cofre_comun", x: chest.x, y: chest.y });

  for (const id of POTION_IDS) {
    const spot = take(spots.find((s) => s.distance >= POTION_MIN_DISTANCE && free(s, POTION_SPACING)));
    if (spot) props.push(item(id, spot));
  }

  const sword = take(spots[spots.length - 1]);
  if (sword) props.push(item("enemy_sword", sword));
  return props;
}

// Centers of floor tiles whose 3x3 neighbourhood is all floor (the item fits
// without touching a wall), nearest to the spawn first.
function openSpots(map: TileMap, spawn: { x: number; y: number }): Spot[] {
  const t = map.tileSize;
  const spots: Spot[] = [];
  for (let row = 1; row < map.rows - 1; row++) {
    for (let col = 1; col < map.cols - 1; col++) {
      if (!allFloor(map, col, row)) continue;
      const x = col * t + t / 2;
      const y = (row + 1) * t - 4;
      spots.push({ x, y, distance: Math.hypot(x - spawn.x, y - spawn.y) });
    }
  }
  return spots.sort((a, b) => a.distance - b.distance);
}

function allFloor(map: TileMap, col: number, row: number): boolean {
  for (let r = row - 1; r <= row + 1; r++) {
    for (let c = col - 1; c <= col + 1; c++) {
      if (map.isWall(c, r)) return false;
    }
  }
  return true;
}

function item(id: string, spot: Spot): Prop {
  const kind = ITEMS[id];
  return { sprite: kind.sprite, frame: kind.frame, x: spot.x, y: spot.y, pickup: kind };
}
